baseURL = "https://deltai.github.io/"
languageCode = 'en-us'
title = "Deltai Blog"
theme = "PaperMod"
[params]
  math = true

[params.author]
  name  = "Jean Paul"
  email = "Jean.Paul.Achilles@gmail.com"